# Generated by Django 4.2.6 on 2024-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='50FC2FF82F', editable=False, max_length=50),
        ),
    ]
