# Generated by Django 4.2.1 on 2023-11-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Users'},
        ),
    ]
