# Generated by Django 4.2.6 on 2023-11-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_emp',
            field=models.BooleanField(default=False),
        ),
    ]
