# Generated by Django 4.2.6 on 2023-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='5A9FC', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
