# Generated by Django 4.2.6 on 2023-12-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='A812A', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
