# Generated by Django 4.2.6 on 2023-12-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_employee_emp_id_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='718D268177', editable=False, max_length=50),
        ),
    ]
