# Generated by Django 4.2.6 on 2023-12-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='E008362239', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='uploads/user.png', upload_to='uploads/emp//% Y/% m/% d/'),
        ),
    ]
