# Generated by Django 4.2.6 on 2023-12-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_employee_emp_id_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='A1D1D50E69', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='uploads/user.png', upload_to='uploads/emp/'),
        ),
    ]
