# Generated by Django 4.2.6 on 2023-12-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_employee_emp_id_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='2F821EDBFA', editable=False, max_length=50),
        ),
    ]
