# Generated by Django 4.2.6 on 2023-12-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='C683FAB4DD', editable=False, max_length=50),
        ),
    ]
