# Generated by Django 4.2.6 on 2023-12-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='1CF2B7AF4E', editable=False, max_length=50),
        ),
    ]
