# Generated by Django 4.2.6 on 2024-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_employee_emp_id_onlineuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='B629A39241', editable=False, max_length=50),
        ),
    ]
