# Generated by Django 4.2.1 on 2023-11-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_created_at_alter_client_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
