# Generated by Django 4.2.6 on 2023-12-21 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notification', '0004_alter_notification_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notifications',
        ),
    ]
