# Generated by Django 4.2.6 on 2023-12-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_rename_notification_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
