# Generated by Django 4.2.1 on 2023-11-10 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0006_alter_projects_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Task Title', max_length=100)),
                ('description', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
                ('task_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ongoing', 'On Going'), ('notstarted', 'Not started'), ('completed', 'Completed')], default='notstarted', max_length=10)),
                ('priority', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.projects')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'ordering': ['-id'],
            },
        ),
    ]
