# Generated by Django 4.2.6 on 2024-01-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('broadcast_on', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-broadcast_on'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_files/')),
                ('file_name', models.TextField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Task Title', max_length=100)),
                ('description', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
                ('task_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('todo', 'To Do'), ('doing', 'Doing'), ('completed', 'Completed')], default='notstarted', max_length=10)),
                ('priority', models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('low', 'Low')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'ordering': ['-id'],
            },
        ),
    ]
