# Generated by Django 4.2.6 on 2023-11-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('low', 'Low')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('todo', 'To Do'), ('doing', 'Doing'), ('completed', 'Completed')], default='notstarted', max_length=10),
        ),
    ]
