# Generated by Django 4.2.6 on 2023-12-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
