# Generated by Django 4.2.1 on 2023-10-30 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Projec Title', max_length=100)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
                ('project_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('project_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('progress', models.IntegerField(default=0, max_length=10)),
                ('status', models.CharField(choices=[('ongoing', 'On Going'), ('notstarted', 'Not started'), ('completed', 'Completed')], default='notstarted', max_length=10)),
                ('priority', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('low', 'Low')], default='low', max_length=10)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
