# Generated by Django 4.2.6 on 2024-01-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project Title', max_length=100)),
                ('description', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
                ('project_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('inprogress', 'In Progress'), ('notstarted', 'Not started'), ('onhold', 'On Hold'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='notstarted', max_length=10)),
                ('priority', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('low', 'Low')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-id'],
            },
        ),
    ]
