# Generated by Django 4.2.6 on 2024-01-09 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0041_alter_employee_emp_id'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_created',
        ),
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(to='users.employee'),
        ),
        migrations.AddField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(default='Project Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In Progress'), ('notstarted', 'Not started'), ('onhold', 'On Hold'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='notstarted', max_length=10),
        ),
    ]
