# Generated by Django 4.2.1 on 2023-10-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
