# Generated by Django 4.2.1 on 2023-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_projects_project_created_projects_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(default='Project Title', max_length=100),
        ),
    ]
