# Generated by Django 4.2.1 on 2023-11-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projects_description_alter_projects_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Projects'},
        ),
    ]
