# Generated by Django 4.2.6 on 2023-11-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projects_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In Progress'), ('notstarted', 'Not started'), ('onhold', 'On Hold'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='notstarted', max_length=10),
        ),
    ]
