# Generated by Django 4.2.6 on 2023-12-21 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_options_and_more'),
        ('project', '0007_alter_projects_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsNotifications',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.NOTIFICATIONS_NOTIFICATION_MODEL)),
                ('type', models.CharField(default=None, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
            bases=('notifications.notification',),
        ),
    ]
