# Generated by Django 4.2.6 on 2023-12-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_pmsnotifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PmsNotifications',
        ),
    ]
