# Generated by Django 4.2.6 on 2023-12-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_notification_type_notification_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
