# Generated by Django 4.2.6 on 2023-12-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_employee_emp_id'),
        ('project', '0012_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(to='users.employee'),
        ),
    ]
